# Generated by Django 2.0.6 on 2018-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Spanish', 'Spanish'), ('Chinese', 'Chinese'), ('French', 'French')], default='English', help_text='Language of the book', max_length=100),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
